<<<<<<< HEAD
theme: jekyll-theme-architect

sidebar:
  - title: "Title"
    image: https://image.shutterstock.com/image-photo/herd-cows-green-meadow-below-450w-1352305955.jpg
    image_alt: "image"
    text: "Some text here."
  - title: "Another Title"
    text: "More text here."
    nav: sidebar-sample
=======
theme: jekyll-theme-slate
>>>>>>> 98f010ec1112062bc3b06e86ee07be747f1fa57b
